// ==UserScript==
// @name         Verify You Are Human
// @namespace    https://tampermonkey.net/
// @version      1.10.1
// @author       MuKonqi
// @description  A user-script for fake combination of Cloudflare's Tunnel and Google's reCAPTCHA.
// @copyright    Copyright (C) 2025-2026 MuKonqi
// @homepageURL  https://github.com/mukonqi/fake-captcha
// @supportURL   https://github.com/mukonqi/fake-captcha/issues
// @updateURL    https://raw.githubusercontent.com/mukonqi/fake-captcha/main/script.meta.js
// @downloadURL  https://raw.githubusercontent.com/mukonqi/fake-captcha/main/script.user.js
// @match        https://*.islamansiklopedisi.org.tr/*
// @match        https://*.medyajans.com/*
// @match        https://*.superhaber.tv/*
// @match        https://*.ntv.com.tr/*
// @match        https://*.haber7.com/*
// @match        https://*.cnnturk.com/*
// @match        https://*.ensonhaber.com/*
// @match        https://*.ahaber.com.tr/*
// @match        https://*.trthaber.com/*
// @match        https://*.haberturk.com/*
// @match        https://*.aa.com.tr/*
// @match        https://*.t24.com.tr/*
// @match        https://*.iha.com.tr/*
// @match        https://*.odatv.com/*
// @match        https://*.odatv4.com/*
// @match        https://*.dha.com.tr/*
// @match        https://*.veryansintv.com/*
// @match        https://*.bbc.com/turkce/*
// @match        https://*.gercekgundem.com/*
// @match        https://*.tr.sputniknews.com/*
// @match        https://*.diken.com.tr/*
// @match        https://*.amerikaninsesi.com/*
// @match        https://*.haberler.com/*
// @match        https://*.tr.euronews.com/*
// @match        https://*.f5haber.com/*
// @match        https://*.tv100.com/*
// @match        https://*.beyazgazete.com/*
// @match        https://*.indyturk.com/*
// @match        https://*.diyanethaber.com.tr/*
// @match        https://*.trhaber.com/*
// @match        https://*.memurlar.net/*
// @match        https://*.gazetevatan.com/*
// @match        https://*.haber3.com/*
// @match        https://*.stargazete.com/*
// @match        https://*.internethaber.com/*
// @match        https://*.referansmedya.com/*
// @match        https://*.timeturk.com/*
// @match        https://*.sondakika.com/*
// @match        https://*.medyafaresi.com/*
// @match        https://*.medyascope.tv/*
// @match        https://*.mynet.com/*
// @match        https://*.turktime.com/*
// @match        https://*.hurhaber.com/*
// @match        https://*.objektifhaber.com/*
// @match        https://*.habervakti.com/*
// @match        https://*.eurovizyon.co.uk/*
// @match        https://*.habervitrini.com/*
// @match        https://*.bigpara.com/*
// @match        https://*.arkeolojikhaber.com/*
// @match        https://*.acunn.com/*
// @match        https://*.bianet.org/*
// @match        https://*.tgrthaber.com.tr/*
// @match        https://*.haber.sol.org.tr/*
// @match        https://*.haberet.com/*
// @match        https://*.agos.com.tr/*
// @match        https://*.aksam.com.tr/*
// @match        https://*.posta.com.tr/*
// @match        https://*.karar.com/*
// @match        https://*.aydinlik.com.tr/*
// @match        https://*.sabah.com.tr/*
// @match        https://*.cumhuriyet.com.tr/*
// @match        https://*.yenisafak.com.tr/*
// @match        https://*.yenimesaj.com.tr/*
// @match        https://*.gazetebirlik.com/*
// @match        https://*.balkangunlugu.com.tr/*
// @match        https://*.medyaradar.com/*
// @match        https://*.televizyongazetesi.com/*
// @match        https://*.medyatava.com/*
// @match        https://*.marketingturkiye.com/*
// @match        https://*.gazeteciler.com/*
// @match        https://*.mediacatonline.com/*
// @match        https://*.dorduncukuvvetmedya.com/*
// @match        https://*.ranini.tv/*
// @match        https://*.medyaloji.net/*
// @match        https://*.journo.com.tr/*
// @match        https://*.medyakafe.com/*
// @match        https://*.onedio.com/*
// @match        https://*.gzt.com/*
// @match        https://*.neoldu.com/*
// @match        https://*.incisozluk.com.tr/*
// @match        https://*.eksisozluk.com/*
// @match        https://*.listelist.com/*
// @match        https://*.fikircografyasi.com/*
// @match        https://*.fikriyat.com/*
// @match        https://*.kizlarsoruyor.com/*
// @match        https://*.abcgazetesi.com/*
// @match        https://*.aksam.com.tr/*
// @match        https://*.artigercek.com/*
// @match        https://*.aydinlik.com.tr/*
// @match        https://*.birgun.net/*
// @match        https://*.bloomberght.com/*
// @match        https://*.cumhuriyet.com.tr/*
// @match        https://*.dogruhaber.com.tr/*
// @match        https://*.dunya.com/*
// @match        https://*.evrensel.net/*
// @match        https://*.fanatik.com.tr/*
// @match        https://*.fotomac.com.tr/*
// @match        https://*.fotospor.com/*
// @match        https://*.gazeteduvar.com.tr/*
// @match        https://*.gazetepencere.com/*
// @match        https://*.gozlemgazetesi.com/*
// @match        https://*.gunes.com/*
// @match        https://*.habercem.com/*
// @match        https://*.haberport.com/*
// @match        https://*.hurriyet.com.tr/*
// @match        https://*.karar.com/*
// @match        https://*.korkusuz.com.tr/*
// @match        https://*.milatgazetesi.com/*
// @match        https://*.milligazete.com.tr/*
// @match        https://*.milliyet.com.tr/*
// @match        https://*.nefesgazetesi.com/*
// @match        https://*.onedio.com/*
// @match        https://*.posta.com.tr/*
// @match        https://*.pressturk.com/*
// @match        https://*.rasthaber.com/*
// @match        https://*.sabah.com.tr/*
// @match        https://*.sonsoz.com.tr/*
// @match        https://*.sozcu.com.tr/*
// @match        https://*.star.com.tr/*
// @match        https://*.sokgazetesi.com.tr/*
// @match        https://*.takvim.com.tr/*
// @match        https://*.turkgun.com/*
// @match        https://*.turkiyegazetesi.com.tr/*
// @match        https://*.yazarhaber.com.tr/*
// @match        https://*.yeniakit.com.tr/*
// @match        https://*.yeniasir.com.tr/*
// @match        https://*.yeniasya.com.tr/*
// @match        https://*.yenicaggazetesi.com.tr/*
// @match        https://*.yenimesaj.com.tr/*
// @match        https://*.yenisoz.com.tr/*
// @match        https://*.yenisafak.com/*
// @match        https://*.yurtgazetesi.com.tr/*
// @match        https://*.yurttansesler.org/*
// @match        https://*.analizgazetesi.com.tr/*
// @match        https://*.breakingnews.com.tr/*
// @match        https://*.britannica.com/*
// @match        https://*.cumhuriyetdaily.com/*
// @match        https://*.dailysabah.com/*
// @match        https://*.denizhaber.net/*
// @match        https://*.ekonomihatti.net/*
// @match        https://*.gazetebanka.com/*
// @match        https://*.haberchannel.com/*
// @match        https://*.hurriyetdailynews.com/*
// @match        https://*.isghaber.com.tr/*
// @match        https://*.isigmeclisi.org/*
// @match        https://*.medimagazin.com.tr/*
// @match        https://*.sendika.org/*
// @match        https://*.sputnikglobe.com/*
// @icon         https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/RecaptchaLogo.svg/150px-RecaptchaLogo.svg.png
// @grant        none
// @run-at       document-start
// ==/UserScript==